from features.steps.src.commands.command_interface.movable import Movable


class AutoGeneratedMovableAdapter(Movable):
    def __init__(self, obj, ioc):
        self.obj = obj
        self.ioc = ioc

    def add(self, x, y):
        return self.ioc.resolve("Movable.add", x, y
                                ).execute()

    def get_position(self):
        return self.ioc.resolve("Movable.get_position", "position"
                                ).execute()

    def get_velocity(self):
        return self.ioc.resolve("Movable.get_velocity", "velocity"
                                ).execute()

    def set_position(self, new_value):
        return self.ioc.resolve("Movable.set_position", "position", new_value
                                ).execute()

    def set_velocity(self, new_value):
        return self.ioc.resolve("Movable.set_velocity", "velocity", new_value
                                ).execute()
