from features.steps.src.commands.command_interface.rotable import Rotable


class AutoGeneratedRotableAdapter(Rotable):
    def __init__(self, obj, ioc):
        self.obj = obj
        self.ioc = ioc

    def get_angular_velocity(self):
        return self.ioc.resolve("Rotable.get_angular_velocity",
                                "angular_velocity"
                                ).execute()

    def get_direction(self):
        return self.ioc.resolve("Rotable.get_direction", "direction"
                                ).execute()

    def get_directions_number(self):
        return self.ioc.resolve("Rotable.get_directions_number",
                                "directions_number"
                                ).execute()

    def set_angular_velocity(self, new_value):
        return self.ioc.resolve("Rotable.set_angular_velocity",
                                "angular_velocity", new_value
                                ).execute()

    def set_direction(self, new_value):
        return self.ioc.resolve("Rotable.set_direction",
                                "direction",
                                new_value
                                ).execute()

    def set_directions_number(self, new_value):
        return self.ioc.resolve("Rotable.set_directions_number",
                                "directions_number",
                                new_value
                                ).execute()
