from tests.test_data.imovable import TankOperationsIMovable


class AutoGeneratedTankOperationsIMovableAdapter(TankOperationsIMovable):
    def __init__(self, obj, ioc):
        self.obj = obj
        self.ioc = ioc

    def getPosition(self):
        return self.ioc.resolve("TankOperationsIMovable.getPosition",
                                ).execute()

    def getVelocity(self):
        return self.ioc.resolve("TankOperationsIMovable.getVelocity",
                                ).execute()

    def setPosition(self, value):
        return self.ioc.resolve("TankOperationsIMovable.setPosition", value
                                ).execute()
